// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260227165731_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.TrainingDay", b =>
                {
                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.HasKey("Date");

                    b.ToTable("TrainingDays");
                });

            modelBuilder.Entity("Domain.Entities.TrainingInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("DurationTimeInMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateOnly>("TrainingDayDate")
                        .HasColumnType("date");

                    b.Property<int>("TrainingStatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrainingDayDate");

                    b.HasIndex("TrainingStatusId");

                    b.ToTable("TrainingInfos", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.TrainingStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CodeName")
                        .IsUnique()
                        .HasDatabaseName("IX_TrainingStatuses_CodeName");

                    b.ToTable("TrainingStatuses", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.TrainingInfo", b =>
                {
                    b.HasOne("Domain.Entities.TrainingDay", "TrainingDay")
                        .WithMany("TrainingInfo")
                        .HasForeignKey("TrainingDayDate")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.TrainingStatus", "TrainingStatus")
                        .WithMany()
                        .HasForeignKey("TrainingStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TrainingDay");

                    b.Navigation("TrainingStatus");
                });

            modelBuilder.Entity("Domain.Entities.TrainingDay", b =>
                {
                    b.Navigation("TrainingInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
